# Variables
resize_step=5

# General settings
set -g update-environment "SSH_AUTH_SOCK LANG LC_CTYPE LC_ALL TERM EDITOR VISUAL PAGER LESS PATH"
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"
set -s escape-time 0
setw -g mode-keys vi
set -g status-keys vi

# Key bindings
bind r command-prompt "rename-window %%"

# Mouse
set -g mouse on

# Clipboard
set -g set-clipboard on
setw -g mode-keys vi
bind-key -T copy-mode-vi y send -X copy-selection-and-cancel

# Pane management
is_vim="ps -o state= -o comm= -t '#{pane_tty}' \
  | grep -iqE '^[^TXZ ]+ +(\S+\/)?g?(view|n?vim?x?)(diff)?$'"

bind ";" split-window -h -c "#{pane_current_path}"
bind "/" split-window -v -c "#{pane_current_path}" 
unbind '"'
unbind %

bind -n C-h if-shell "$is_vim" "send-keys C-h" "select-pane -L"
bind -n C-j if-shell "$is_vim" "send-keys C-j" "select-pane -D"
bind -n C-k if-shell "$is_vim" "send-keys C-k" "select-pane -U"
bind -n C-l if-shell "$is_vim" "send-keys C-l" "select-pane -R"

bind -n M-C-h if-shell "$is_vim" "send-keys M-h" "resize-pane -L $resize_step"
bind -n M-C-j if-shell "$is_vim" "send-keys M-j" "resize-pane -D $resize_step"
bind -n M-C-k if-shell "$is_vim" "send-keys M-k" "resize-pane -U $resize_step"
bind -n M-C-l if-shell "$is_vim" "send-keys M-l" "resize-pane -R $resize_step"

# Window management
bind -n M-h previous-window
bind -n M-l next-window


set-window-option -g pane-border-status bottom
set -g pane-border-format ""

# ----------------------------
# Status bar 
# ----------------------------
set -g status-right "%H:%M | %d-%m-%Y "

# Inactive text: soft gray 
set -g status-style fg=colour255

# Inactive panes slightly dim
set -g window-style fg=colour240,bg=default
# Active pane normal
set -g window-active-style fg=colour255,bg=default

# ----------------------------
# Pane borders (all muted gray)
# ----------------------------
set -g pane-border-style fg=colour248
set -g pane-active-border-style fg=colour248  

# ----------------------------
# Messages / prompts
# ----------------------------
set -g message-style fg=colour255 # transparent bg

# Copy / mode style
set -g mode-style bg=colour250,fg=colour0
